name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt-get install mesa-common-dev libx11-dev libxcursor-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxi-dev libgl1-mesa-dev
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Build BGFX Release + examples
        run: cargo build --release --example cubes --example helloworld
  build_emscripten:
    name: Build Emscripten
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Emscripten
        uses: mymindstorm/setup-emsdk@v11
      - name: Install emscripten Rust tools 
        run: rustup target add wasm32-unknown-emscripten
      - name: Build Web example 
        run: cd web_example && cargo build --target=wasm32-unknown-emscripten


